#pragma once

#define SERIAL_USART_FULL_DUPLEX
#define SERIAL_USART_TX_PIN GP0
#define SERIAL_USART_RX_PIN GP1
#define SERIAL_USART_PIN_SWAP
#define SERIAL_USART_SPEED 921600
#define USB_VBUS_PIN GP19

#define COMBO_ONLY_FROM_LAYER 0
